[package]
name = "value-trait"
version = "0.2.12"
authors = ["Heinz N. Gies <heinz@licenser.net>"]
edition = "2021"
license = "Apache-2.0/MIT"
description = "Traits to deal with JSONesque values"
repository = "https://github.com/simd-lite/value-trait"
readme = "README.md"
documentation = "https://docs.rs/value-trait"
rust-version = "1.59"


[dependencies]
itoa = { version = "0.4", features = ["i128"] }
ryu = "1"
halfbrown = "0.1"
float-cmp = "0.9"

# abi_stable = { version = "0.10.3", optional = true, default-features = false }
abi_stable = { version = "0.11.0", optional = true, default_features = false, features = ["rust_latest_stable", "halfbrown"], git = "https://github.com/marioortizmanero/abi_stable_crates.git", branch = "halfbrown" }

[features]
# Support for 128 bit integers
128bit = []

# Support for custom types
custom-types = []

# Support for abi-stable's `StableAbi` implementation
c-abi = ["abi_stable"]
